name: Example workflow to push to hitachi_demo3

on:
  push:
    branches: [ main ]
	
jobs:
  repo_copy:
    runs-on: ubuntu-latest
	steps:
	  - uses: actions/checkout@v3
	  - name: Use_secrets
	    run: echo ${{secrets.HITACHI_TOKEN}}
		
	  - name: copy to new repo
	    run:
		  #- add a repote repo
		  git remote add origin https://${{secrets.HITACHI_TOKEN}}github.com/Adityaanuj/hitachi-demo3.git
		  git push upstream main

